import { useState, type ComponentType } from "react";
import { useNavigate } from "@tanstack/react-router";
import { Activity, Bot, Braces, Cable, ChartNoAxesCombined, Database, Flame, GitBranch, Globe, History, House, Menu, Plug, Search, Settings, ShieldCheck, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Sheet,SheetContent,SheetTitle,SheetTrigger } from "@/components/ui/sheet";
import { cn } from "@/lib/utils";
import type { Section } from "@/types/flameflow";
import { useProject } from "@/context/ProjectContext";
const items:{id:Section;label:string;icon:ComponentType<{className?:string}>}[]=[
 {id:"overview",label:"Overview",icon:House},{id:"users",label:"Users",icon:Users},{id:"database",label:"Database",icon:Database},{id:"analytics",label:"Analytics",icon:ChartNoAxesCombined},{id:"seo",label:"SEO & GEO",icon:Search},{id:"domain",label:"Domain",icon:Globe},{id:"integrations",label:"Integrations",icon:Plug},{id:"security",label:"Security",icon:ShieldCheck},{id:"agents",label:"Agents",icon:Bot},{id:"workflows",label:"Workflows",icon:GitBranch},{id:"logs",label:"Logs",icon:History},{id:"api",label:"API",icon:Braces},{id:"settings",label:"Settings",icon:Settings},{id:"mcp",label:"MCP",icon:Cable}];
function SideContent({section,onSelect}:{section:Section;onSelect:()=>void}){const [query,setQuery]=useState("");const nav=items.filter(x=>x.label.toLowerCase().includes(query.toLowerCase()));const navigate=useNavigate();const {state}=useProject();return <div className="flex h-full flex-col bg-sidebar px-4 py-5"><div className="mb-5 flex items-center gap-3 px-2"><div className="grid size-9 place-items-center rounded-lg bg-brand text-brand-foreground"><Flame className="size-5"/></div><div><p className="font-semibold">Flameflow</p><p className="text-xs text-muted-foreground">Project console</p></div></div><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input aria-label="Search navigation" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search..." className="h-10 bg-background pl-9"/>{query&&<Button variant="ghost" size="icon" className="absolute right-1 top-0.5 size-9" onClick={()=>setQuery("")} aria-label="Clear search"><X/></Button>}</div><nav className="mt-5 min-h-0 flex-1 space-y-1 overflow-y-auto" aria-label="Project navigation">{nav.map(({id,label,icon:Icon})=><button key={id} onClick={()=>{navigate({to:"/dashboard",search:{projectId:state.project.id,section:id}});onSelect()}} className={cn("flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-left text-sm transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",section===id?"bg-sidebar-accent font-medium text-sidebar-accent-foreground":"text-sidebar-foreground hover:bg-sidebar-accent/60")}><Icon className="size-[18px] shrink-0"/>{label}</button>)}{nav.length===0&&<p className="px-3 py-8 text-center text-sm text-muted-foreground">No results found</p>}</nav><div className="mt-5 border-t border-sidebar-border pt-4"><div className="flex items-center gap-3 rounded-md px-2 py-2"><div className="grid size-8 shrink-0 place-items-center rounded-md bg-logo text-logo-foreground"><Activity className="size-4"/></div><div className="min-w-0"><p className="truncate text-sm font-medium">{state.project.name}</p><p className="truncate text-xs text-muted-foreground">{state.project.id} · Production</p></div></div></div></div>}
export function AppShell({section,children}:{section:Section;children:React.ReactNode}){const [open,setOpen]=useState(false);return <div className="min-h-screen overflow-x-hidden bg-background"><aside className="fixed inset-y-0 left-0 z-30 hidden w-80 border-r border-sidebar-border lg:block"><SideContent section={section} onSelect={()=>{}}/></aside><div className="min-w-0 lg:pl-80"><div className="sticky top-0 z-20 flex h-14 items-center border-b border-border bg-background/95 px-4 backdrop-blur lg:hidden"><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><Button variant="ghost" size="icon" aria-label="Open navigation"><Menu/></Button></SheetTrigger><SheetContent side="left" className="w-[min(290px,calc(100vw-24px))] p-0"><SheetTitle className="sr-only">Project navigation</SheetTitle><SideContent section={section} onSelect={()=>setOpen(false)}/></SheetContent></Sheet><span className="ml-3 text-sm font-semibold">Flameflow</span></div><main className="mx-auto min-w-0 max-w-[1440px] px-4 py-7 sm:px-7 lg:px-10 lg:py-10">{children}</main></div></div>}
