import type { ReactNode } from "react";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
export function PageHeader({title,subtitle,action}:{title:string;subtitle:string;action?:ReactNode}){return <header className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-4"><div className="min-w-0"><h1 className="text-2xl font-semibold text-foreground sm:text-[28px]">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{subtitle}</p></div>{action&&<div className="shrink-0">{action}</div>}</header>}
export function Panel({children,className}:{children:ReactNode;className?:string}){return <section className={cn("rounded-lg border border-border bg-card p-5",className)}>{children}</section>}
export function PanelTitle({title,description,action}:{title:string;description?:string;action?:ReactNode}){return <div className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-4"><div className="min-w-0"><h2 className="font-semibold text-foreground">{title}</h2>{description&&<p className="mt-1 text-sm leading-5 text-muted-foreground">{description}</p>}</div>{action}</div>}
export function Status({children,tone="neutral"}:{children:ReactNode;tone?:"neutral"|"success"|"warning"|"danger"|"info"}){return <Badge variant="outline" className={cn("font-medium",tone==="success"&&"border-success/25 bg-success-soft text-success",tone==="warning"&&"border-warning/25 bg-warning-soft text-warning",tone==="danger"&&"border-destructive/25 bg-destructive-soft text-destructive",tone==="info"&&"border-info/25 bg-info-soft text-info")}>{children}</Badge>}
export function Metric({label,value,detail}:{label:string;value:string;detail?:string}){return <Panel className="min-h-28"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-3 text-2xl font-semibold text-foreground">{value}</p>{detail&&<p className="mt-1 text-xs text-muted-foreground">{detail}</p>}</Panel>}
export function Empty({title,description}:{title:string;description:string}){return <div className="grid min-h-48 place-items-center rounded-lg border border-dashed border-border bg-muted/30 p-8 text-center"><div><p className="font-medium">{title}</p><p className="mt-1 max-w-md text-sm text-muted-foreground">{description}</p></div></div>}
